version: '3.1'
services:
  dbNorline:
    container_name: DB
    image: postgres
    user: root
    ports:
      - "5432:5432"
    #networks:
    #  - my-network
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17      
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odooNorline:
    container_name: Odoo
    image: odoo:17.0
    user: root
    depends_on:
      - dbNorline
    ports:
      - "10032:8069"
      - "20032:8072" # live chat
   # networks:
   #   - my-network
    tty: true
    command: -- --db_host=dbNorline --db_port=5432 --db_user=odoo --db_password=odoo17
    environment:
      - HOST=dbNorline
      - USER=odoo
      - PASSWORD=odoo17
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./extra-addons:/mnt/extra-addons
      - ./health:/mnt/custom-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
#networks:
#  my-network:
#      external: true
